import type { Business, Connection, Device, Rack } from "./types";

export const businesses: Business[] = [
  {
    id: "acme",
    name: "Acme Manufacturing",
    sites: ["HQ MDF", "Warehouse IDF", "Front Office"],
  },
  {
    id: "northstar",
    name: "Northstar Dental",
    sites: ["Clinic MDF", "Operatories"],
  },
];

export const racks: Rack[] = [
  {
    id: "rack-a",
    businessId: "acme",
    site: "HQ MDF",
    name: "Rack A",
    sizeU: 24,
    role: "Core switching and gateway",
  },
  {
    id: "rack-b",
    businessId: "acme",
    site: "Warehouse IDF",
    name: "Rack B",
    sizeU: 18,
    role: "Warehouse distribution",
  },
  {
    id: "rack-c",
    businessId: "acme",
    site: "Front Office",
    name: "Rack C",
    sizeU: 12,
    role: "Office access and cameras",
  },
  {
    id: "rack-d",
    businessId: "northstar",
    site: "Clinic MDF",
    name: "Rack D",
    sizeU: 18,
    role: "Clinic network core",
  },
];

export const devices: Device[] = [
  {
    id: "udm-se",
    rackId: "rack-a",
    name: "UDM SE",
    model: "UniFi Dream Machine SE",
    type: "gateway",
    uStart: 22,
    heightU: 1,
    status: "online",
    ip: "10.20.0.1",
    ports: [
      { id: "udm-wan", label: "WAN", speed: "2.5G", connectedTo: "ISP Fiber ONT" },
      { id: "udm-10g", label: "SFP+ 11", speed: "10G", vlan: "Trunk", connectedTo: "USW-Aggregation 1" },
      { id: "udm-p1", label: "Port 1", speed: "1G", vlan: "Mgmt", connectedTo: "Cloud Key Spare" },
    ],
  },
  {
    id: "agg",
    rackId: "rack-a",
    name: "Aggregation",
    model: "USW-Aggregation",
    type: "switch",
    uStart: 20,
    heightU: 1,
    status: "online",
    ip: "10.20.0.2",
    ports: [
      { id: "agg-1", label: "SFP+ 1", speed: "10G", vlan: "Trunk", connectedTo: "UDM SE SFP+ 11" },
      { id: "agg-2", label: "SFP+ 2", speed: "10G", vlan: "Trunk", connectedTo: "Rack B USW-Pro-24" },
      { id: "agg-3", label: "SFP+ 3", speed: "10G", vlan: "Trunk", connectedTo: "Rack C USW-24-PoE" },
      { id: "agg-4", label: "SFP+ 4", speed: "10G", connectedTo: "Future NVR" },
    ],
  },
  {
    id: "core-poe",
    rackId: "rack-a",
    name: "Core PoE",
    model: "USW-Pro-48-PoE",
    type: "switch",
    uStart: 17,
    heightU: 1,
    status: "online",
    ip: "10.20.0.3",
    ports: [
      { id: "core-1", label: "1", speed: "1G", vlan: "Corp", connectedTo: "Conference AP" },
      { id: "core-2", label: "2", speed: "1G", vlan: "Voice", connectedTo: "Reception Phone" },
      { id: "core-3", label: "3", speed: "1G", vlan: "Camera", connectedTo: "Parking Lot G4" },
      { id: "core-48", label: "48", speed: "1G", vlan: "Trunk", connectedTo: "Patch Panel 24" },
    ],
  },
  {
    id: "patch-a",
    rackId: "rack-a",
    name: "Patch Panel",
    model: "24 port Cat6",
    type: "patch",
    uStart: 15,
    heightU: 1,
    status: "planned",
    ports: [
      { id: "patch-a-1", label: "01", speed: "1G", vlan: "Corp", connectedTo: "Office 101" },
      { id: "patch-a-2", label: "02", speed: "1G", vlan: "Voice", connectedTo: "Office 101 Phone" },
      { id: "patch-a-3", label: "03", speed: "1G", vlan: "Camera", connectedTo: "North Door" },
      { id: "patch-a-4", label: "04", speed: "1G", connectedTo: "Open" },
    ],
  },
  {
    id: "warehouse-switch",
    rackId: "rack-b",
    name: "Warehouse PoE",
    model: "USW-Pro-24-PoE",
    type: "switch",
    uStart: 16,
    heightU: 1,
    status: "online",
    ip: "10.30.0.2",
    ports: [
      { id: "wh-1", label: "1", speed: "1G", vlan: "Scanner", connectedTo: "Dock AP" },
      { id: "wh-2", label: "2", speed: "1G", vlan: "Camera", connectedTo: "Bay 1 Camera" },
      { id: "wh-24", label: "24", speed: "1G", vlan: "Trunk", connectedTo: "Patch Panel B" },
      { id: "wh-sfp", label: "SFP+ 1", speed: "10G", vlan: "Trunk", connectedTo: "Rack A Aggregation" },
    ],
  },
  {
    id: "office-switch",
    rackId: "rack-c",
    name: "Office Access",
    model: "USW-24-PoE",
    type: "switch",
    uStart: 10,
    heightU: 1,
    status: "attention",
    ip: "10.40.0.2",
    ports: [
      { id: "of-1", label: "1", speed: "1G", vlan: "Corp", connectedTo: "Open Office AP" },
      { id: "of-2", label: "2", speed: "1G", vlan: "Guest", connectedTo: "Lobby AP" },
      { id: "of-12", label: "12", speed: "100M", vlan: "Printer", connectedTo: "Finance Printer" },
      { id: "of-sfp", label: "SFP 1", speed: "1G", vlan: "Trunk", connectedTo: "Rack A Aggregation" },
    ],
  },
  {
    id: "clinic-core",
    rackId: "rack-d",
    name: "Clinic Gateway",
    model: "UDM Pro",
    type: "gateway",
    uStart: 16,
    heightU: 1,
    status: "online",
    ip: "10.70.0.1",
    ports: [
      { id: "cl-wan", label: "WAN", speed: "1G", connectedTo: "ISP modem" },
      { id: "cl-1", label: "LAN 1", speed: "1G", vlan: "Clinical", connectedTo: "Treatment switch" },
      { id: "cl-2", label: "LAN 2", speed: "1G", vlan: "Guest", connectedTo: "Guest AP" },
    ],
  },
];

export const connections: Connection[] = [
  {
    id: "uplink-a-b",
    fromRackId: "rack-a",
    toRackId: "rack-b",
    fromDevice: "Aggregation",
    toDevice: "Warehouse PoE",
    medium: "10G fiber",
    status: "active",
  },
  {
    id: "uplink-a-c",
    fromRackId: "rack-a",
    toRackId: "rack-c",
    fromDevice: "Aggregation",
    toDevice: "Office Access",
    medium: "1G fiber",
    status: "constrained",
  },
  {
    id: "future-nvr",
    fromRackId: "rack-a",
    toRackId: "rack-a",
    fromDevice: "Aggregation",
    toDevice: "Future NVR",
    medium: "10G DAC",
    status: "planned",
  },
];
